// <auto-generated>
// Verbatim copy of Tools/CliHarness/scenarios/ppe_inspection.json, embedded as a string
// constant so the integration fixture can parse the REAL PPEInspection scenario through
// ScenarioLoader.Parse without any file IO — keeping the test headless-portable (Unity Editor
// test assembly AND the standalone .NET test project in T3). If the source scenario changes,
// regenerate this file. Engine-independent (no UnityEngine).
// </auto-generated>
namespace SafetyProto.Tests.Editor.Support
{
    public static class PpeInspectionScenarioJson
    {
        public const string Value = @"{
  ""name"": ""PPEInspection"",
  ""participantId"": ""P001"",
  ""groups"": [
    {
      ""name"": ""Seleção de EPIs"",
      ""executionMode"": ""Sequential"",
      ""timeLimit"": 270,
      ""tasks"": [
        {
          ""name"": ""Equipar Botina de Segurança"",
          ""successPoints"": 100,
          ""requiredPPE"": [""Boots""],
          ""hintText"": ""Escolha um calçado de segurança fechado, adequado aos riscos do canteiro e com CA válido."",
          ""taskDescription"": ""Selecione a botina de segurança correta e equipe nos pés.""
        },
        {
          ""name"": ""Equipar Luvas de Proteção"",
          ""successPoints"": 200,
          ""requiredPPE"": [""Boots"", ""GloveLeft"", ""GloveRight""],
          ""hintText"": ""Escolha luvas adequadas ao manuseio de estruturas metálicas e proteja as duas mãos."",
          ""taskDescription"": ""Selecione as luvas adequadas e equipe nas duas mãos.""
        },
        {
          ""name"": ""Equipar Óculos de Proteção"",
          ""successPoints"": 100,
          ""requiredPPE"": [""Boots"", ""GloveLeft"", ""GloveRight"", ""Goggles""],
          ""hintText"": ""Escolha uma proteção ocular adequada contra partículas e respingos."",
          ""taskDescription"": ""Selecione os óculos de proteção e equipe no rosto.""
        },
        {
          ""name"": ""Equipar Capacete com Jugular"",
          ""successPoints"": 150,
          ""requiredPPE"": [""Boots"", ""GloveLeft"", ""GloveRight"", ""Goggles"", ""Helmet""],
          ""hintText"": ""Escolha o capacete com jugular para mantê-lo preso à cabeça durante o trabalho em altura."",
          ""taskDescription"": ""Selecione o capacete CORRETO (com jugular) e equipe na cabeça.""
        },
        {
          ""name"": ""Equipar Cinto Paraquedista"",
          ""successPoints"": 200,
          ""requiredPPE"": [""Boots"", ""GloveLeft"", ""GloveRight"", ""Goggles"", ""Helmet"", ""Harness""],
          ""hintText"": ""Para retenção de queda, escolha o cinturão de segurança tipo paraquedista; o cinto abdominal não é adequado a esse sistema."",
          ""taskDescription"": ""Selecione o cinto tipo paraquedista e vista corretamente.""
        }
      ]
    },
    {
      ""name"": ""Inspeção em Andaime Fachadeiro"",
      ""executionMode"": ""FreeOrder"",
      ""timeLimit"": 300,
      ""requiredGroups"": [""Seleção de EPIs""],
      ""tasks"": [
        {
          ""name"": ""Conectar Talabarte ao Ponto de Ancoragem"",
          ""actionId"": ""connect_harness"",
          ""successPoints"": 200,
          ""failurePenalty"": 50,
          ""ppePenalty"": 50,
          ""requiredPPE"": [""Harness"", ""Helmet""],
          ""hintText"": ""Conecte o talabarte ao ponto de ancoragem indicado antes de se expor ao risco e permaneça conectado durante a atividade."",
          ""ppeAdvice"": ""Você conectou o talabarte, mas estava sem algum EPI obrigatório. Verifique todos os equipamentos ANTES de subir."",
          ""failureAdvice"": ""Conectar o talabarte ao ponto de ancoragem certificado é a primeira ação ao chegar na plataforma. Trabalhar desconectado é a principal causa de quedas fatais."",
          ""taskDescription"": ""Conecte o talabarte do cinto ao ponto de ancoragem certificado na estrutura.""
        },
        {
          ""name"": ""Instalar Guarda-corpo"",
          ""actionId"": ""install_guardrail"",
          ""successPoints"": 200,
          ""failurePenalty"": 50,
          ""ppePenalty"": 50,
          ""requiredPPE"": [""Harness"", ""Helmet"", ""GloveLeft"", ""GloveRight""],
          ""hintText"": ""Verifique todo o perímetro aberto: o guarda-corpo deve ter travessão superior a 1,20 m, intermediário a 0,70 m e rodapé (NR-18, itens 18.9.4.2 e 18.12.1 'd')."",
          ""ppeAdvice"": ""Instalar o guarda-corpo sem luvas de proteção e/ou capacete expõe suas mãos a cortes nas estruturas metálicas."",
          ""failureAdvice"": ""O guarda-corpo deve estar presente em todos os lados abertos da plataforma (NR-18 §18.15). Sua ausência expõe trabalhadores a queda direta."",
          ""taskDescription"": ""Instale a seção de guarda-corpo faltante no lado direito da plataforma.""
        },
        {
          ""name"": ""Instalar Rodapé"",
          ""actionId"": ""install_toeboard"",
          ""successPoints"": 150,
          ""failurePenalty"": 50,
          ""ppePenalty"": 50,
          ""requiredPPE"": [""Harness"", ""Helmet"", ""GloveLeft"", ""GloveRight""],
          ""hintText"": ""Verifique a base do guarda-corpo: o rodapé deve ter no mínimo 15 cm e impedir a queda de materiais (NR-18, item 18.9.4.2 'c')."",
          ""ppeAdvice"": ""Manipular peças metálicas sem luvas é uma violação de segurança."",
          ""failureAdvice"": ""O rodapé de 20cm impede que ferramentas e materiais caiam da plataforma sobre trabalhadores abaixo (NR-18 §18.15)."",
          ""taskDescription"": ""Instale o rodapé de 20cm na seção faltante da plataforma.""
        },
        {
          ""id"": ""report_damaged_safety_mesh"",
          ""name"": ""Reportar Irregularidade na Tela Fachadeira"",
          ""actionId"": ""flag_safety_net"",
          ""successPoints"": 100,
          ""failurePenalty"": 30,
          ""ppePenalty"": 30,
          ""requiredPPE"": [""Harness"", ""Helmet""],
          ""hintText"": ""Verifique a continuidade da tela e seus pontos de fixação. Rasgos, partes soltas ou amarrações rompidas comprometem a proteção."",
          ""ppeAdvice"": ""A inspeção deve ser realizada com os EPIs obrigatórios e com o talabarte conectado durante a exposição ao risco de queda."",
          ""failureAdvice"": ""A tela estava rasgada e com um ponto de amarração rompido. Essa condição compromete a barreira contra a projeção e a queda de materiais e ferramentas. A irregularidade deve ser reportada antes da liberação da atividade (NR-18, itens 18.12.15 e 18.12.15.1)."",
          ""taskDescription"": ""Inspecione a tela fachadeira e reporte a irregularidade encontrada.""
        }
      ]
    }
  ],
  ""script"": [
    { ""kind"": ""ppe"", ""ppeType"": ""Boots"",      ""isWearing"": true, ""delayMs"": 200 },
    { ""kind"": ""ppe"", ""ppeType"": ""GloveRight"", ""isWearing"": true, ""delayMs"": 200 },
    { ""kind"": ""ppe"", ""ppeType"": ""GloveLeft"",  ""isWearing"": true, ""delayMs"": 200 },
    { ""kind"": ""ppe"", ""ppeType"": ""Goggles"",    ""isWearing"": true, ""delayMs"": 200 },
    { ""kind"": ""ppe"", ""ppeType"": ""Helmet"",     ""isWearing"": true, ""delayMs"": 200 },
    { ""kind"": ""ppe"", ""ppeType"": ""Harness"",    ""isWearing"": true, ""delayMs"": 200 },

    { ""kind"": ""action"", ""actionId"": ""connect_harness"",   ""delayMs"": 200 },
    { ""kind"": ""action"", ""actionId"": ""install_guardrail"", ""delayMs"": 200 },
    { ""kind"": ""action"", ""actionId"": ""install_toeboard"",  ""delayMs"": 200 },
    { ""kind"": ""action"", ""actionId"": ""flag_safety_net"",   ""delayMs"": 200 }
  ]
}
";
    }
}
